version: '3'
services:
  app:
    build: .
    ports:
      - "8888:8888"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://$(DB_USER):$(DB_PASSWORD)@db:5432/$(DB_NAME)?sslmode=disable"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d